### ISSUE TITLE
wysiwyg

### ISSUE THREAD

**Issue by thetoxicarcade** [kauzoj/kauzoj.github.io#14]
```
<script src="https://get.mavo.io/mavo.js"></script>
<link rel="stylesheet" href="https://get.mavo.io/mavo.css">
```

**Comment by Thetoxicarcade** [comment]
mode to edit code in other templates & generate them, or just WYSIWYG with the current/new article?

**Comment by Thetoxicarcade** [comment]
development branch edit mode / pull from development/master? Switch.

**Comment by Thetoxicarcade** [comment]
https://github.com/klokantech/jekylledit
https://github.com/pagina-io/api.pagina.io
https://github.com/pagina-io/pagina.io
https://github.com/swanson/lanyon

**Comment by Thetoxicarcade** [comment]
https://github.com/iamdanfox/ghupdate
https://github.com/mavoweb/mavo-create
https://github.com/colaborativa/jekyllxhibit
https://github.com/front/prose.io
https://github.com/samanpwbb/idle
https://github.com/alecgorge/MarkdownEditor
